### ISSUE TITLE
Error while trying to load from pixbuf after scaling (mismatched types)

### ISSUE THREAD

**Issue by swanux** [gtk-rs/gdk-pixbuf#141]
I'm trying to load images to a pixbuf and after that loading them into a GtkImage from Glade file, but I always get an error message during compile. Here I gave more details: https://stackoverflow.com/questions/60212129/rust-gtk-set-gtkimage-from-pixbuf-using-glade-file

**Comment by GuillaumeGomez** [comment]
The problem here is your lack of knowledge of Rust itself... Try replacing this:

```
let pixbuf = Pixbuf::new_from_file_at_scale(
        "/home/daniel/RUST/test/src/test.gif",
        600,
        700,
        false);
    img2.set_from_pixbuf(Some(&pixbuf));
```

With this:

```
let pixbuf = Pixbuf::new_from_file_at_scale(
        "/home/daniel/RUST/test/src/test.gif",
        600,
        700,
        false).expect("failed to create Pixbuf");
    img2.set_from_pixbuf(Some(&pixbuf));
```

**Comment by swanux** [comment]
Thank you for the answer! First of all, excuse my dumb question, now I've realized how stupid it's... You're right about it, I'm coming from Python and only began learning Rust 2 days ago (without any previous experience with Rust or any C language). Sorry again, and thank you very much!
