### ISSUE TITLE
Status of new_from_data

### ISSUE THREAD

**Issue by danielronnkvist** [gtk-rs/gdk-pixbuf#144]
I have image buffer data loaded using Rust std File. When looking for ways to create a new Pixbuf from that buffer data I found the new_from_data method that was commented. Where there issues implementing a binding? Any other reason why it hasn't been implemented?

https://github.com/gtk-rs/gdk-pixbuf/blob/acbab2328dd62e2cdea083b5919bb728fd98a485/src/auto/pixbuf.rs#L72-L74

**Comment by GuillaumeGomez** [comment]
Isn't `new_from_bytes` working for you?

**Comment by danielronnkvist** [comment]
@GuillaumeGomez Yes it is but I was only curious.
