### ISSUE TITLE
SVG support on Windows

### ISSUE THREAD

**Issue by PonasKovas** [gtk-rs/gdk-pixbuf#163]
I have followed [this guide](https://gtk-rs.org/docs-src/tutorial/cross) to crosscompile my GTK app to Windows, and everything seems to work fine, except that it doesn't recognize the SVG image format.

I tried also adding librsvg-2-2.dll, but that didn't seem to change anything. Any ideas what could be the problem?

Using gdk_pixbuf::Pixbuf::get_formats() returns these:
"ani" - "Windows animated cursor"
"png" - "PNG"
"bmp" - "BMP"
"gif" - "GIF"
"ico" - "Windows icon"
"jpeg" - "JPEG"
"pnm" - "PNM/PBM/PGM/PPM"
"tiff" - "TIFF"
"xpm" - "XPM"
"xbm" - "XBM"
"tga" - "Targa"
"icns" - "MacOS X icon"
"jpeg2000" - "JPEG 2000"
"qtif" - "QuickTime"

**Comment by sdroege** [comment]
You need to have the librsvg pixbuf loader built and installed.

This is not related to the bindings though, and also the issue tracker is no support forum. Please ask at https://discourse.gnome.org . Thanks!
