### ISSUE TITLE
Pixbuf::new_from_surface

### ISSUE THREAD

**Issue by zaari** [gtk-rs/gdk-pixbuf#22]
Please, add support for function `Gdk.pixbuf_get_from_surface(surface, src_x, src_y, width, height)`. As far as I know, it's the only way to render a pixbuf.

**Comment by GuillaumeGomez** [comment]
@Epashkin: Do you know why it isn't generated by any chance?

**Comment by EPashkin** [comment]
Its function without object.

**Comment by EPashkin** [comment]
It done now http://gtk-rs.org/docs/gdk/fn.pixbuf_get_from_surface.html

**Comment by EPashkin** [comment]
@GuillaumeGomez Please close this PR, its done

**Comment by GuillaumeGomez** [comment]
Ok!
