### ISSUE TITLE
Loading Pixbuf non-blocking way

### ISSUE THREAD

**Issue by zaari** [gtk-rs/gdk-pixbuf#23]
Loading Pixbufs in separate threads seem not to be possible. Gtk-rs documentation says that "calling any gtk or gdk functions (including init) from other threads will panic". It wouldn't be possible to Send Pixbufs between the threads anyway. 

Also, gtk-rs doesn't support asynchronous I/O of glib. 

Please, implement a mechanism to load Pixbuf without blocking the GTK main thread.

**Comment by sdroege** [comment]
Pixbufs and most things in gdk-pixbuf should actually be Send but not Sync. But due to refcounting they can't be Send without being Sync
