### ISSUE TITLE
gdk::cairo_set_source_pixbuf

### ISSUE THREAD

**Issue by zaari** [gtk-rs/gdk-pixbuf#26]
Function `gdk::cairo_set_source_pixbuf(context, pixbuf, x, pixbuf_y)` is missing. It's needed to draw a `Pixbuf` onto a surface.

**Comment by EPashkin** [comment]
It added http://gtk-rs.org/docs/gdk/prelude/trait.ContextExt.html#tymethod.set_source_pixbuf

**Comment by zaari** [comment]
You are right, thanks.
