### ISSUE TITLE
add GDK_TYPE_PIXBUF

### ISSUE THREAD

**Issue by Susurrus** [gtk-rs/gdk-pixbuf#32]
Necessary for use with `gtk::ListStore::new()`. Note that the `G_TYPE_*` variables have all been mapped to the nice `gtk::type` enum, so maybe there should be a `gdk::Type::Pixbuf`? I think this is the only type constant provided by gdk, but it'd be consistent.

Note that whatever the type of this constant ends up being, it'll need to be easily convertible to `gtk::Type` in order to be used with `gtk::ListStore::new(&[gtk::Type])`.

**Comment by EPashkin** [comment]
You get pixbuf type with `Pixbuf::static_type()`

**Comment by EPashkin** [comment]
Not sure that it constant.

**Comment by Susurrus** [comment]
Awesome, thanks. So `gdk_pixbuf::Pixbuf::static_type()` needs to be used instead of `GDK_TYPE_PIXBUF`. Would there be a good way to document this currently? Like doc comments on `gdk_pixbuf::Pixbuf::static_type` directly that refer to the C-type by name so it's easy to search for?

**Comment by EPashkin** [comment]
`static_type` implemented in macro so IMHO you can't add doc for it.

**Comment by Susurrus** [comment]
Hmmm, I think that's going to make it hard for other people to come over to `gtk-rs` from C, but I think that can be deferred til later. I'm working on an example for the examples repo that includes this usage, so hopefully that'll help people transition while the docs situation is still getting sorted out. Closing this then, thanks again @EPashkin!

**Comment by GuillaumeGomez** [comment]
One thing we should do/finish would be to actually write a tutorial. I started one a long time ago and I think it might be worth to update it and finish it.

**Comment by Susurrus** [comment]
@GuillaumeGomez Is it public?

**Comment by GuillaumeGomez** [comment]
https://github.com/gtk-rs/gtk-rs.github.io/pull/14
