### ISSUE TITLE
PixbufFormat requires &mut for all functions

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gdk-pixbuf#56]
@EPashkin Seems like a bug in GIR. There's no reason to require &mut for all the *getters*, and for the `set_disabled()` setter interior mutability as before seems better.

This is an API change btw

**Comment by EPashkin** [comment]
You meant https://github.com/gtk-rs/glib/pull/249 or something other?

**Comment by EPashkin** [comment]
Sorry, answered too fast. It because it `Boxed` type

**Comment by sdroege** [comment]
No, this here: https://github.com/gtk-rs/gdk-pixbuf/blob/45888822bed65c348a23cb165f1acb6d6a3d8e81/src/auto/pixbuf_format.rs#L22

**Comment by sdroege** [comment]
But all the getters really shouldn't require `&mut` :)

**Comment by EPashkin** [comment]
It because this writen it writen in GdkPixbuf-2.0.gir on instance parameter:
`gdk_pixbuf_format_is_disabled`: `c:type="GdkPixbufFormat*"`
compare with
`pango_font_description_get_family`: `c:type="const PangoFontDescription*"`
We have "const" override to fix this.

**Comment by sdroege** [comment]
Yes it should be overridden
