### ISSUE TITLE
Request bindings for gdk_pixbuf_get_from_window() function be added to this crate

### ISSUE THREAD

**Issue by pwil3058** [gtk-rs/gdk-pixbuf#62]
Availability of this function will enable the writing of programs that take screen snapshots.

E.g. use gdk::Window::get_default_root_window() to get the gdk::Window that represents the full screen and then use gdk_pixbuf_get_from_window(w, x, y, width, height) to get the pixbuf representing a portion of that window and then add it to the clipboard.

**Comment by GuillaumeGomez** [comment]
Done in #63.

**Comment by EPashkin** [comment]
Actually it already generated in Gdk: https://github.com/gtk-rs/gdk/blob/cdb612c726c6b5e507534dcdd1dc549459b3869a/src/window.rs#L181-L187

**Comment by pwil3058** [comment]
I couldn't find it in the documentation.  This seems to be generally true of traits whose names end in ExtManua i.e. they're invisible and only show up as part of a compiler message if you manage to guess the name that the GTK++ function has in Rustl.  But I tested it and the compiler manages to find it.  Thanks.

**Comment by GuillaumeGomez** [comment]
The strange thing is that I didn't find it into the docs...

**Comment by GuillaumeGomez** [comment]
Since it's already there, I'm closing it.
