### ISSUE TITLE
gdk_pixbuf_new() can return NULL on OOM

### ISSUE THREAD

**Issue by federicomenaquintero** [gtk-rs/gdk-pixbuf#96]
`gdk_pixbuf_new()` can return `NULL` if it cannot allocate memory for the pixel buffer.  However, the binding's `Pixbuf::new()` does not contemplate this; it will probably crash in `from_glib_full()`.

I think this needs an API break to return a Result :disappointed:

**Comment by GuillaumeGomez** [comment]
I recall us (gtk-rs developers) having a discussion about this. I was for keeping an `Option` returned but we wanted to get rid of all `Option`s returned as much as possible. However, in this specific case, I think it'd be better to return an `Option`.

@sdroege @EPashkin: What do you think?

**Comment by sdroege** [comment]
> it will probably crash in `from_glib_full()`.

Panic, yes

> @sdroege @EPashkin: What do you think?

The annotations of `gdk_pixbuf_new()` explicitly say that it's `nullable` so we should return an `Option<_>` here. Why/when was this one removed? :) If there are annotations saying that something is `nullable` we should believe that

**Comment by sdroege** [comment]
This was introduced in https://github.com/gtk-rs/gdk-pixbuf/pull/54 (before it was not autogenerated and returned a `Result`).

Problem here is that our gir files are too old

```xml
      <constructor name="new" c:identifier="gdk_pixbuf_new">
        <doc xml:space="preserve">Creates a new #GdkPixbuf structure and allocates a buffer for it.  The
buffer has an optimal rowstride.  Note that the buffer is not cleared;
you will have to fill it completely yourself.</doc>
        <return-value transfer-ownership="full">
          <doc xml:space="preserve">A newly-created #GdkPixbuf with a reference count of 1, or
%NULL if not enough memory could be allocated for the image buffer.</doc>
          <type name="Pixbuf" c:type="GdkPixbuf*"/>
        </return-value>
```

My local version of it has

```xml
      <constructor name="new" c:identifier="gdk_pixbuf_new">
        <doc xml:space="preserve">Creates a new #GdkPixbuf structure and allocates a buffer for it.  The
buffer has an optimal rowstride.  Note that the buffer is not cleared;
you will have to fill it completely yourself.</doc>
        <return-value transfer-ownership="full" nullable="1">
          <doc xml:space="preserve">A newly-created #GdkPixbuf with a reference count of 1, or
%NULL if not enough memory could be allocated for the image buffer.</doc>
          <type name="Pixbuf" c:type="GdkPixbuf*"/>
        </return-value>
```

**Comment by sdroege** [comment]
So we should probably about the gir files to a newer version in general, and then also in this crate here check that the manual code is correct. `Pixbuf::new_from_vec()` can probably also return `None`.

(Also it should take a `AsRef<[u8]>` instead of a `Vec<u8>` but that's a different problem)

**Comment by EPashkin** [comment]
Ubuntu Bionic don't have nullable="1", Cosmic - have,
so it relatively new fix.
https://packages.ubuntu.com/bionic/amd64/libgdk-pixbuf2.0-dev/download
I agree that we need update gir-files.

**Comment by federicomenaquintero** [comment]
The annotations are from https://gitlab.gnome.org/GNOME/gdk-pixbuf/commit/3e8502a8cbe23d2db84bd91d4f775e57522bfdbe FWIW.

**Comment by EPashkin** [comment]
@federicomenaquintero Thanks.

**Comment by federicomenaquintero** [comment]
Oh, huh, I didn't realize this had changed; already had a patch to add a Result by hand.  But you are right, this should be handled by the annotations.
